groups/urls.py
from django.urls import path
from .views import *

app_name = 'groups'

urlpatterns = [
    path('', ListGroup.as_view(template_name = 'group_list.html'), name='all'),
    path('new/', CreateGroup.as_view(template_name = 'group_form.html'), name='create'),
    path('posts/in/<slug:slug>', SingleGroup.as_view(template_name = 'group_detail.html'), name='single'),
    path('join/<slug:slug>', JoinGroup.as_view(), name='join'),
    path('leave/<slug:slug>', LeaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', PostList.as_view(template_name = "post_list.html"), name='all'),
    path('new/', CreatePost.as_view(template_name = "post_form.html"), name='create'),
    path('by/<slug:username>/', UserPosts.as_view(template_name = "user_post_list.html"), name='for_user'),
    path('by/<slug:username>/<int:pk>', PostDetail.as_view(template_name = "post_detail.html"), name='single'),
    path('delete/<int:pk>', DeletePost.as_view(template_name = "post_confirm_delete.html"), name='delete'),

]

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('', include('account.urls', namespace='account')),
    path('', include('django.contrib.auth.urls')),
    path('test/', TestPage.as_view(), name = "test"),
    path('thanks/', ThanksPage.as_view(), name = "thanks"),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),

]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    members = models.ManyToManyField(User, through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('single', kwargs={'slug':self.slug})
    
    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ['group', 'user']

groups/views.py
from django.contrib import messages
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.mixins import (LoginRequiredMixin, 
                                        PermissionRequiredMixin)
from django.urls import reverse 
from django.views.generic import (CreateView, DetailView, ListView, RedirectView)
from .models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(DetailView):
    model = Group

class ListGroup(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, RedirectView):
    login_url = "login"
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug = self.kwargs.get('slug'))

        try: 
            GroupMember.objects.create(user = self.request.user, group = group)
        except IntegrityError:
            messages.warning(self.request, ("Warning already a member!"))
        else:
            messages.warning(self.request, ("You are now a member!"))

        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(user = self.request.user, group__slug=self.kwargs.get('slug')).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, "Sorry, you are not in this group!")
        else:
            membership.delete()
            messages.success(self.request, "You have left the group!")

        return super().get(request, *args, **kwargs)

groups/templates/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}
      
    {% endblock %}
    
    {% block group_content %}

    {% endblock %}

    {% block postgroup %}

    {% endblock %}
  </div>
</div>

{% endblock %}

groups/templates/group_detail.html
{% extends "group_base.html" %}



{% block pregroup %}
<h1>{{ group.name }}</h1>
<h2>Member count: {{ group.members.count }}</h2>
<div class="content">
    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}" 
        class="btn btn-lg btn-fill btn-warning">
            <i class="bi bi-person-x-fill">Leave</i>
        </a>
    {% else %}
        <a href="{% url 'groups:join' slug=group.slug %}" 
        class="btn btn-lg btn-fill btn-warning">
            <i class="bi bi-check-circle-fill">Join</i>
        </a>
    {% endif %}
</div>

{% endblock %}

{% block group_content %}
<div class="col-md-8">
	{% if group.posts.count == 0 %}
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for post in group.posts.all %}
            {% include '_post.html' %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

groups/templates/group_form.html
{% extends "group_base.html" %}
{% load bootstrap5 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

groups/templates/group_list.html
{% extends "group_base.html" %}


{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
			<h2>
				Welcome Back!
				<a href="{% url 'posts:for_user' username=user.username %}">
					@{{ user.username }}
				</a>
			</h2>
		{% endif %}
		<h2>Groups</h2>
		<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
		{% if user.is_authenticated %}
			<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
				<i class="bi bi-plus-circle-fill">Create New Group!</i>
			</a>
		{% endif %}
	</div>
</div>
{% endblock %}



{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
			<a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
				<h3 class="title list-group-item-heading">{{ group.name }}</h3>
				<div class="list-group-item-text container-fluid">
					{{ group.description }}
					<div class="row">
						<div class="col-md-4">
							<span class="badge text-bg-warning">{{group.members.count}}</span>
							member{{group.members.count|pluralize}}
						</div>
						<div class="col-md-4">
							<span class="badge text-bg-warning">{{group.posts.count}}</span>
							post{{group.posts.count|pluralize}}
						</div>
					</div>
				</div>
			</a>
		{% endfor %}
	</div>
</div>
{% endblock %}