account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import SignUp

app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'login.html'), name = 'login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup')
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', PostList.as_view(template_name = "post_list.html"), name='all'),
    path('new/', CreatePost.as_view(template_name = "post_form.html"), name='create'),
    path('by/<slug:username>/', UserPosts.as_view(template_name = "user_post_list.html"), name='for_user'),
    path('by/<slug:username>/<int:pk>', PostDetail.as_view(template_name = "post_detail.html"), name='single'),
    path('delete/<int:pk>', DeletePost.as_view(template_name = "post_confirm_delete.html"), name='delete'),

]

social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home'),
    path('', include('account.urls', namespace='account')),
    path('', include('django.contrib.auth.urls')),
    path('test/', TestPage.as_view(), name = "test"),
    path('thanks/', ThanksPage.as_view(), name = "thanks"),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" role="navigation" id="navbar">
    	<div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
            <ul class="navbar-nav navbar-right navbar-dark text-light">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:create' %}" class="btn btn-simple">Post</a></li>
                    <li><a href="{% url 'groups:all' %}" class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'groups:create' %}" class="btn btn-simple">Create Group</a></li>
                    <li><a href="{% url 'logout' %}" class="btn btn-simple">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'groups:all' %}"class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'login' %}" class="btn btn-simple">Log in</a></li>
                    <li><a href="{% url 'account:signup' %}" class="btn btn-simple">Sign up</a></li>
                {% endif %}
            </ul>
    	</div>
    </nav>
    <div class="container mycontent" style="color: white;">
        {% block content %}

        {% endblock %}
    </div>
    <canvas id="canvas"></canvas>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  <script src="{% static 'js/master.js'%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to Star Social!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
</div>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>Thanks for visiting, come back soon!</h1>
</div>
{% endblock %}